# Generated by Django 5.0rc1 on 2023-11-24 08:33

import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "slug",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Lower(
                            django.db.models.functions.text.Replace(
                                models.F("title"), models.Value(" "), models.Value("-")
                            )
                        ),
                        output_field=models.TextField(),
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
